import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import TelegramLoginButton, { TelegramUser } from "telegram-login-button";
import { Bot, InlineKeyboard } from "grammy";

interface User {
  id: number;
  first_name: string;
  last_name: string;
  username: string;
  photo_url: string;
  auth_date: number;
  hash: string;
}

const Home: NextPage = () => {
  //Store bot screaming status
  let screaming = false;

  const [login, setLogin] = useState(false);
  const [user, setUser] = useState<User>();

  const bot = new Bot("5527167347:AAFg51t0sd4lTYYLJndy7C1XhgKEdj4YoiE");
  // bot reply user button with link
  const sendLinkButton = () => {
    bot.on("message", (ctx: any) => ctx.reply("Hi there!"));
  
  };
  console.log("user.id", user?.id)

  const sendLoungeMessage = async (spaceTitle: string) => {
    const url = "http://ec2-3-37-70-35.ap-northeast-2.compute.amazonaws.com:3000/bot"
    fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        },
        body: JSON.stringify({
          link: spaceTitle,
          id: user?.id,
        })
      })
      .then((res) => {res.json(); console.log(res); })      
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {login ? (
          <>
          <h1>Logged in</h1>
          <button onClick={() => sendLoungeMessage("tonicspace")}>tonicspace</button>
          <button onClick={() => sendLoungeMessage("toniclounge")}>toniclounge</button>

          </>
        ) : (
          <>
          <TelegramLoginButton
            botName="TonicLoungeBot"
            usePic={true}
            dataOnauth={(user: TelegramUser) => {
              setLogin(true);
              console.log(user);
            }}
          />
          <button onClick={() => sendLoungeMessage("tonicspace")}>tonicspace</button>
          <button onClick={() => sendLoungeMessage("toniclounge")}>toniclounge</button>
          </>
        )}

        <button onClick={sendLinkButton}>Send Link</button>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
